### ISSUE TITLE
prevent overriding reports

### ISSUE THREAD

**Issue by ethangodt** [grawk/nemo-runner#10]
In the latest published release if I'm running a test against two profiles, the second test saves it's report files over the first profiles report files because it's using the same name.

e.g. `nemo-runner -P chrome,safari -G @mytest@` will produce:
```
  1 passing (43s)

[mochawesome] Report JSON saved to /tests/functional/nemo/reports/nemo-report_@mytest@.json

[mochawesome] Report HTML saved to /tests/functional/nemo/reports/nemo-report_@mytest@.html

    ✓ blah blah blah (43664ms)

  1 passing (34s)

[mochawesome] Report JSON saved to /tests/functional/nemo/reports/nemo-report_@mytest@.json

[mochawesome] Report HTML saved to /tests/functional/nemo/reports/nemo-report_@mytest@.html

    ✓ blah blah blah (34664ms)

```

and I'll be left with just the one latest test result in `/tests/functional/nemo/reports/nemo-report_@mytest@.html`

**Comment by grawk** [comment]
can we close this one and discuss the solution in #7?

**Comment by ethangodt** [comment]
yep
