### ISSUE TITLE
separate Nemo instances for each Mocha suite

### ISSUE THREAD

**Issue by kweiberth** [grawk/nemo-runner#4]
It would be nice if `nemo-runner` instantiated separate Nemo instances per Mocha suite (aka per `describe` so that we can leverage Saucelabs' parallel execution and individual job reports, screencasts and logs.

@grawk and I have chatted about this offline, and I believe he has started looking into it

**Comment by ethangodt** [comment]
this is resolved right?

**Comment by grawk** [comment]
Yep.
