### ISSUE TITLE
prevent "parallel by file" runs from printing extraneous logs and reports

### ISSUE THREAD

**Issue by ethangodt** [grawk/nemo-runner#8]
In the currently published version, if parallelize by file, `nemo-runner` will scan each file for a grep match and print result to console. If I am trying to match one test out of 100 files, I will get 99 of:
```
0 passing (37ms)

[mochawesome] Report JSON saved to /tests/functional/nemo/reports/nemo-report_@tag@_tests!test.json
```

Somewhat related to https://github.com/paypal/nemo-runner/issues/7 (this problem may not happen if all reports are grouped) but I think ultimately I'm asking if we can ignore the "0 matches" in parallel by file.

**Comment by grawk** [comment]
sounds like, if there are no matching tests based on the inputs, we should not call `mocha.run`.. will take a look and see if that's feasible given the mocha programmatic API.. unless someone beats me to it.
